apiVersion: apiextensions.crossplane.io/v1
kind: Composition

metadata:
  name: applicationserver-composition

spec:
  compositeTypeRef:
    apiVersion: platform.parimal.io/v1alpha1
    kind: ApplicationServer

  writeConnectionSecretsToNamespace: crossplane-system

  resources:
    # -------------------------
    # S3 Bucket
    # -------------------------
    - name: bucket

      base:
        apiVersion: s3.aws.upbound.io/v1beta1
        kind: Bucket

        spec:
          forProvider:
            region: us-east-1

          providerConfigRef:
            name: default

      patches:
        - type: FromCompositeFieldPath
          fromFieldPath: spec.bucketName
          toFieldPath: metadata.name

    # -------------------------
    # EC2 Instance
    # -------------------------
    # - name: instance

    #   base:
    #     apiVersion: ec2.aws.upbound.io/v1beta2
    #     kind: Instance

    #     spec:
    #       forProvider:
    #         region: us-east-1

    #         ami: ami-0521cb2d60cfbb1a6

    #         subnetId: subnet-06d49ab0d2e7eb7a0

    #         availabilityZone: us-east-1a

    #         instanceType: t3.micro

    #       providerConfigRef:
    #         name: default

    #   patches:
    #     - type: FromCompositeFieldPath
    #       fromFieldPath: spec.instanceType
    #       toFieldPath: spec.forProvider.instanceType
    #     - type: FromCompositeFieldPath
    #       fromFieldPath: metadata.name
    #       toFieldPath: metadata.name
