apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition

metadata:
  name: s3buckets.platform.local

spec:
  group: platform.local

  names:
    kind: S3Bucket
    plural: s3buckets

  versions:
    - name: v1alpha1
      served: true
      referenceable: true

      schema:
        openAPIV3Schema:
          type: object

          properties:
            spec:
              type: object

              properties:
                bucketName:
                  type: string

              required:
                - bucketName
