apiVersion: platform.parimal.io/v1alpha1
kind: ApplicationServer

metadata:
  name: demo-app

spec:
  # instanceType: t3.micro
  bucketName: parimal-storage-543098

  securityGroups:
    - web
    - rds
